# Generated by Django 4.1 on 2022-08-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('other_service', models.TextField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('our_contacts', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp', models.URLField()),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='OurPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partner', models.CharField(max_length=255)),
                ('urls_partner', models.URLField()),
                ('logo', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendationHotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='')),
                ('contacts', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='')),
                ('whatsapp', models.URLField()),
                ('telegram', models.URLField()),
                ('instagram', models.URLField()),
            ],
        ),
    ]
